//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SWX {
    
    private SWXCASEINFO cASEINFOField;
    
    private SWXFOLDER fOLDERField;
    
    /// <remarks/>
    public SWXCASEINFO CASEINFO {
        get {
            return this.cASEINFOField;
        }
        set {
            this.cASEINFOField = value;
        }
    }
    
    /// <remarks/>
    public SWXFOLDER FOLDER {
        get {
            return this.fOLDERField;
        }
        set {
            this.fOLDERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SWXCASEINFO {
    
    private string nameField;
    
    private string backColorField;
    
    private string backBmpField;
    
    private string largeFontField;
    
    private string smallFontField;
    
    private string fontColorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BackColor {
        get {
            return this.backColorField;
        }
        set {
            this.backColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BackBmp {
        get {
            return this.backBmpField;
        }
        set {
            this.backBmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LargeFont {
        get {
            return this.largeFontField;
        }
        set {
            this.largeFontField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SmallFont {
        get {
            return this.smallFontField;
        }
        set {
            this.smallFontField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FontColor {
        get {
            return this.fontColorField;
        }
        set {
            this.fontColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SWXFOLDER {
    
    private object[] itemsField;
    
    private string nameField;
    
    private byte levelField;
    
    private string searchableField;
    
    private string checkedField;
    
    private string expandedField;
    
    private byte treeIDField;
    
    private byte typeField;
    
    private string scriptField;
    
    private string extraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FOLDER", typeof(SWXFOLDERFOLDER))]
    [System.Xml.Serialization.XmlElementAttribute("ITEM", typeof(SWXFOLDERITEM))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Searchable {
        get {
            return this.searchableField;
        }
        set {
            this.searchableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Checked {
        get {
            return this.checkedField;
        }
        set {
            this.checkedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Expanded {
        get {
            return this.expandedField;
        }
        set {
            this.expandedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte TreeID {
        get {
            return this.treeIDField;
        }
        set {
            this.treeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Script {
        get {
            return this.scriptField;
        }
        set {
            this.scriptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Extra {
        get {
            return this.extraField;
        }
        set {
            this.extraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SWXFOLDERFOLDER {
    
    private SWXFOLDERFOLDERITEM[] iTEMField;
    
    private string nameField;
    
    private byte levelField;
    
    private string searchableField;
    
    private string checkedField;
    
    private string expandedField;
    
    private ushort treeIDField;
    
    private byte typeField;
    
    private string scriptField;
    
    private string extraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ITEM")]
    public SWXFOLDERFOLDERITEM[] ITEM {
        get {
            return this.iTEMField;
        }
        set {
            this.iTEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Searchable {
        get {
            return this.searchableField;
        }
        set {
            this.searchableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Checked {
        get {
            return this.checkedField;
        }
        set {
            this.checkedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Expanded {
        get {
            return this.expandedField;
        }
        set {
            this.expandedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort TreeID {
        get {
            return this.treeIDField;
        }
        set {
            this.treeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Script {
        get {
            return this.scriptField;
        }
        set {
            this.scriptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Extra {
        get {
            return this.extraField;
        }
        set {
            this.extraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SWXFOLDERFOLDERITEM {
    
    private string nameField;
    
    private byte levelField;
    
    private string searchableField;
    
    private string checkedField;
    
    private string expandedField;
    
    private ushort treeIDField;
    
    private byte typeField;
    
    private string scriptField;
    
    private string extraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Searchable {
        get {
            return this.searchableField;
        }
        set {
            this.searchableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Checked {
        get {
            return this.checkedField;
        }
        set {
            this.checkedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Expanded {
        get {
            return this.expandedField;
        }
        set {
            this.expandedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort TreeID {
        get {
            return this.treeIDField;
        }
        set {
            this.treeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Script {
        get {
            return this.scriptField;
        }
        set {
            this.scriptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Extra {
        get {
            return this.extraField;
        }
        set {
            this.extraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SWXFOLDERITEM {
    
    private string nameField;
    
    private byte levelField;
    
    private string searchableField;
    
    private string checkedField;
    
    private string expandedField;
    
    private ushort treeIDField;
    
    private byte typeField;
    
    private string scriptField;
    
    private string extraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Searchable {
        get {
            return this.searchableField;
        }
        set {
            this.searchableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Checked {
        get {
            return this.checkedField;
        }
        set {
            this.checkedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Expanded {
        get {
            return this.expandedField;
        }
        set {
            this.expandedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort TreeID {
        get {
            return this.treeIDField;
        }
        set {
            this.treeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Script {
        get {
            return this.scriptField;
        }
        set {
            this.scriptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Extra {
        get {
            return this.extraField;
        }
        set {
            this.extraField = value;
        }
    }
}
